### ISSUE TITLE
Investigate SqlException That Occurred During Backup

### ISSUE THREAD

**Issue by JazzGlobal** [MonitoringSolutionsInc/DatabaseBackupTool#42]
This happened when attempting to backup the attached databases. I haven't seen this error before but the ONLY thing I can think of is that it's because I replaced my hard drive. I'll look more into this. 

This only occurred on the Sys1 and Sys2, not the AVG, MIN and SCAN DBs generated today. 

`2021-06-02 16:59:16.1975 An Error Occurred While Attempting to Backup Database: CargillSaltSys1 System.Data.SqlClient.SqlException (0x80131904): Cannot use the backup file 'C:\CEMDAS\temp\CargillSaltSys1.BAK' because it was originally formatted with sector size 512 and is now on a device with sector size 4096.
BACKUP DATABASE is terminating abnormally.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader()
   at SqlConnector.SQLConnector.ReadResults(SqlCommand sqlCommand) in G:\code\SQLConnector\SqlConnector\SqlConnection.cs:line 142
   at DatabaseBackupTool.Backup.backgroundWorker3_DoWork(Object sender, DoWorkEventArgs e) in D:\code\DatabaseBackupTool\DatabaseBackupTool\Backup.cs:line 359
ClientConnectionId:e0ac0b31-8478-4b05-8af4-84cb1655c271
Error Number:3268,State:1,Class:16`

**Comment by JazzGlobal** [comment]
Previous assumption was wrong. This is caused by the fact that I restored the .BAK file from an external hard drive and then attempted to back it up onto an SSD. This issue also occurred when attempting to backup the database using SSMS.
